/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlueprintsIndexRouteImport } from './routes/blueprints/index'
import { Route as BlueprintsAddRouteImport } from './routes/blueprints/add'
import { Route as BlueprintsBlueprintIdRouteImport } from './routes/blueprints/$blueprintId'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintsIndexRoute = BlueprintsIndexRouteImport.update({
  id: '/blueprints/',
  path: '/blueprints/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintsAddRoute = BlueprintsAddRouteImport.update({
  id: '/blueprints/add',
  path: '/blueprints/add',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintsBlueprintIdRoute = BlueprintsBlueprintIdRouteImport.update({
  id: '/blueprints/$blueprintId',
  path: '/blueprints/$blueprintId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/blueprints/$blueprintId': typeof BlueprintsBlueprintIdRoute
  '/blueprints/add': typeof BlueprintsAddRoute
  '/blueprints': typeof BlueprintsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/blueprints/$blueprintId': typeof BlueprintsBlueprintIdRoute
  '/blueprints/add': typeof BlueprintsAddRoute
  '/blueprints': typeof BlueprintsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/blueprints/$blueprintId': typeof BlueprintsBlueprintIdRoute
  '/blueprints/add': typeof BlueprintsAddRoute
  '/blueprints/': typeof BlueprintsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/blueprints/$blueprintId'
    | '/blueprints/add'
    | '/blueprints'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/blueprints/$blueprintId'
    | '/blueprints/add'
    | '/blueprints'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/blueprints/$blueprintId'
    | '/blueprints/add'
    | '/blueprints/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  BlueprintsBlueprintIdRoute: typeof BlueprintsBlueprintIdRoute
  BlueprintsAddRoute: typeof BlueprintsAddRoute
  BlueprintsIndexRoute: typeof BlueprintsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprints/': {
      id: '/blueprints/'
      path: '/blueprints'
      fullPath: '/blueprints'
      preLoaderRoute: typeof BlueprintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprints/add': {
      id: '/blueprints/add'
      path: '/blueprints/add'
      fullPath: '/blueprints/add'
      preLoaderRoute: typeof BlueprintsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprints/$blueprintId': {
      id: '/blueprints/$blueprintId'
      path: '/blueprints/$blueprintId'
      fullPath: '/blueprints/$blueprintId'
      preLoaderRoute: typeof BlueprintsBlueprintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  BlueprintsBlueprintIdRoute: BlueprintsBlueprintIdRoute,
  BlueprintsAddRoute: BlueprintsAddRoute,
  BlueprintsIndexRoute: BlueprintsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
