/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedBlueprintsIndexRouteImport } from './routes/_authenticated/blueprints/index'
import { Route as AuthenticatedBlueprintsBrowseRouteImport } from './routes/_authenticated/blueprints/browse'
import { Route as AuthenticatedBlueprintsAddRouteImport } from './routes/_authenticated/blueprints/add'
import { Route as AuthenticatedBlueprintsBlueprintIdRouteImport } from './routes/_authenticated/blueprints/$blueprintId'
import { Route as AuthenticatedBlueprintsBlueprintIdPreviewRouteImport } from './routes/_authenticated/blueprints/_.$blueprintId.preview'
import { Route as AuthenticatedBlueprintsBlueprintIdEditRouteImport } from './routes/_authenticated/blueprints/_.$blueprintId.edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBlueprintsIndexRoute =
  AuthenticatedBlueprintsIndexRouteImport.update({
    id: '/blueprints/',
    path: '/blueprints/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBlueprintsBrowseRoute =
  AuthenticatedBlueprintsBrowseRouteImport.update({
    id: '/blueprints/browse',
    path: '/blueprints/browse',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBlueprintsAddRoute =
  AuthenticatedBlueprintsAddRouteImport.update({
    id: '/blueprints/add',
    path: '/blueprints/add',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBlueprintsBlueprintIdRoute =
  AuthenticatedBlueprintsBlueprintIdRouteImport.update({
    id: '/blueprints/$blueprintId',
    path: '/blueprints/$blueprintId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBlueprintsBlueprintIdPreviewRoute =
  AuthenticatedBlueprintsBlueprintIdPreviewRouteImport.update({
    id: '/blueprints/_/$blueprintId/preview',
    path: '/blueprints/$blueprintId/preview',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBlueprintsBlueprintIdEditRoute =
  AuthenticatedBlueprintsBlueprintIdEditRouteImport.update({
    id: '/blueprints/_/$blueprintId/edit',
    path: '/blueprints/$blueprintId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/blueprints/$blueprintId': typeof AuthenticatedBlueprintsBlueprintIdRoute
  '/blueprints/add': typeof AuthenticatedBlueprintsAddRoute
  '/blueprints/browse': typeof AuthenticatedBlueprintsBrowseRoute
  '/blueprints/': typeof AuthenticatedBlueprintsIndexRoute
  '/blueprints/$blueprintId/edit': typeof AuthenticatedBlueprintsBlueprintIdEditRoute
  '/blueprints/$blueprintId/preview': typeof AuthenticatedBlueprintsBlueprintIdPreviewRoute
}
export interface FileRoutesByTo {
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/blueprints/$blueprintId': typeof AuthenticatedBlueprintsBlueprintIdRoute
  '/blueprints/add': typeof AuthenticatedBlueprintsAddRoute
  '/blueprints/browse': typeof AuthenticatedBlueprintsBrowseRoute
  '/blueprints': typeof AuthenticatedBlueprintsIndexRoute
  '/blueprints/$blueprintId/edit': typeof AuthenticatedBlueprintsBlueprintIdEditRoute
  '/blueprints/$blueprintId/preview': typeof AuthenticatedBlueprintsBlueprintIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/blueprints/$blueprintId': typeof AuthenticatedBlueprintsBlueprintIdRoute
  '/_authenticated/blueprints/add': typeof AuthenticatedBlueprintsAddRoute
  '/_authenticated/blueprints/browse': typeof AuthenticatedBlueprintsBrowseRoute
  '/_authenticated/blueprints/': typeof AuthenticatedBlueprintsIndexRoute
  '/_authenticated/blueprints/_/$blueprintId/edit': typeof AuthenticatedBlueprintsBlueprintIdEditRoute
  '/_authenticated/blueprints/_/$blueprintId/preview': typeof AuthenticatedBlueprintsBlueprintIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/auth/login'
    | '/blueprints/$blueprintId'
    | '/blueprints/add'
    | '/blueprints/browse'
    | '/blueprints/'
    | '/blueprints/$blueprintId/edit'
    | '/blueprints/$blueprintId/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/profile'
    | '/auth/login'
    | '/'
    | '/blueprints/$blueprintId'
    | '/blueprints/add'
    | '/blueprints/browse'
    | '/blueprints'
    | '/blueprints/$blueprintId/edit'
    | '/blueprints/$blueprintId/preview'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/profile'
    | '/auth/login'
    | '/_authenticated/'
    | '/_authenticated/blueprints/$blueprintId'
    | '/_authenticated/blueprints/add'
    | '/_authenticated/blueprints/browse'
    | '/_authenticated/blueprints/'
    | '/_authenticated/blueprints/_/$blueprintId/edit'
    | '/_authenticated/blueprints/_/$blueprintId/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/blueprints/': {
      id: '/_authenticated/blueprints/'
      path: '/blueprints'
      fullPath: '/blueprints/'
      preLoaderRoute: typeof AuthenticatedBlueprintsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/blueprints/browse': {
      id: '/_authenticated/blueprints/browse'
      path: '/blueprints/browse'
      fullPath: '/blueprints/browse'
      preLoaderRoute: typeof AuthenticatedBlueprintsBrowseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/blueprints/add': {
      id: '/_authenticated/blueprints/add'
      path: '/blueprints/add'
      fullPath: '/blueprints/add'
      preLoaderRoute: typeof AuthenticatedBlueprintsAddRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/blueprints/$blueprintId': {
      id: '/_authenticated/blueprints/$blueprintId'
      path: '/blueprints/$blueprintId'
      fullPath: '/blueprints/$blueprintId'
      preLoaderRoute: typeof AuthenticatedBlueprintsBlueprintIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/blueprints/_/$blueprintId/preview': {
      id: '/_authenticated/blueprints/_/$blueprintId/preview'
      path: '/blueprints/$blueprintId/preview'
      fullPath: '/blueprints/$blueprintId/preview'
      preLoaderRoute: typeof AuthenticatedBlueprintsBlueprintIdPreviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/blueprints/_/$blueprintId/edit': {
      id: '/_authenticated/blueprints/_/$blueprintId/edit'
      path: '/blueprints/$blueprintId/edit'
      fullPath: '/blueprints/$blueprintId/edit'
      preLoaderRoute: typeof AuthenticatedBlueprintsBlueprintIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBlueprintsBlueprintIdRoute: typeof AuthenticatedBlueprintsBlueprintIdRoute
  AuthenticatedBlueprintsAddRoute: typeof AuthenticatedBlueprintsAddRoute
  AuthenticatedBlueprintsBrowseRoute: typeof AuthenticatedBlueprintsBrowseRoute
  AuthenticatedBlueprintsIndexRoute: typeof AuthenticatedBlueprintsIndexRoute
  AuthenticatedBlueprintsBlueprintIdEditRoute: typeof AuthenticatedBlueprintsBlueprintIdEditRoute
  AuthenticatedBlueprintsBlueprintIdPreviewRoute: typeof AuthenticatedBlueprintsBlueprintIdPreviewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBlueprintsBlueprintIdRoute:
    AuthenticatedBlueprintsBlueprintIdRoute,
  AuthenticatedBlueprintsAddRoute: AuthenticatedBlueprintsAddRoute,
  AuthenticatedBlueprintsBrowseRoute: AuthenticatedBlueprintsBrowseRoute,
  AuthenticatedBlueprintsIndexRoute: AuthenticatedBlueprintsIndexRoute,
  AuthenticatedBlueprintsBlueprintIdEditRoute:
    AuthenticatedBlueprintsBlueprintIdEditRoute,
  AuthenticatedBlueprintsBlueprintIdPreviewRoute:
    AuthenticatedBlueprintsBlueprintIdPreviewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
